# Generated by Django 5.0.4 on 2024-05-22 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['user'], name='app_quiz_user_id_fcaad8_idx'),
        ),
    ]
